stages:
  - mirror

mirror-to-github:
  stage: mirror
  variables:
    GIT_DEPTH: 0   # full clone, needed for mirroring
  script:
    - git config --global user.email "gitlab-ci@testing.com"
    - git config --global user.name "GitLab CI"

    - git remote remove github || true
    - git remote add github https://oauth2:${GITHUB_TOKEN}@github.com/ratheeshpr89/Testing_me.git

    # Debug info
    - git fetch --all
    - git remote -v
    - git log --oneline | head -n 5

    # Push with verbosity
    - git push --mirror github -v
  only:
    - schedules
  tags:
    - git_hub_mirror
