stages:
  - mirror

mirror-to-github:
  stage: mirror
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: 0
  script:
    - git config --global user.email "gitlab-ci@testing.com"
    - git config --global user.name "GitLab CI"

    - git remote remove github || true
    - git remote add github https://oauth2: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@github.com/ratheeshpr89/Testing_mePo.git

    # Push the same branch that triggered the pipeline
    - git push github HEAD:$CI_COMMIT_REF_NAME

    # Push tags
    - git push github --tags

  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

  tags:
    - git_hub_mirror