stages:
  - mirror

mirror-to-github:
  stage: mirror
  variables:
    GIT_DEPTH: 0   # ensure full repo
  script:
    - git config --global user.email "gitlab-ci@testing.com"
    - git config --global user.name "GitLab CI"

    - git remote remove github || true
    - git remote add github https://oauth2:${GITHUB_TOKEN}@github.com/ratheeshpr89/Testing_mePo.git

    - git fetch --all
    - git remote -v

    # Push main branch explicitly
    - git push github HEAD:refs/heads/main
    # Push all tags
    - git push github --tags
  only:
    - schedules
  tags:
    - git_hub_mirror
