stages:
  - mirror

stages:
  - mirror

mirror-to-github:
  stage: mirror
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: 0
  script:
    - git config --global user.email "gitlab-ci@testing.com"
    - git config --global user.name "GitLab CI"

    # Add GitHub remote
    - git remote add github https://ratheeshpr89:${GITHUB_TOKEN}@github.com/ratheeshpr89/Testing_mePo.git

    # Mirror everything (branches + tags)
    - git push --mirror github

  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

  tags:
    - git_hub_mirror

