stages:
  - mirror

mirror-to-github:
  stage: mirror
  variables:
    GIT_DEPTH: 0   # ensure full repo history
  script:
    # Set Git identity
    - git config --global user.email "gitlab-ci@testing.com"
    - git config --global user.name "GitLab CI"

    # Add GitHub remote (remove if exists)
    - git remote remove github || true
    - git remote add github https://oauth2:${GITHUB_TOKEN}@github.com/ratheeshpr89/Testing_mePo.git

    # Fetch all branches and tags from GitLab
    - git fetch --all

    # Push all branches to GitHub
    - git push github --all

    # Push all tags to GitHub
    - git push github --tags

    # Optional: verify remotes
    - git remote -v

  only:
    - schedules
  tags:
    - git_hub_mirror

